"""
Action Tools — Generate and execute operational actions.
Used by the Action Execution Agent.
"""

import json
from datetime import datetime


def draft_supplier_email(
    supplier_name: str,
    supplier_contact: str,
    disruption_context: str,
    ask: str,
    sender_name: str = "Supply Chain Operations Team",
    company_name: str = "AutomotiveParts GmbH"
) -> dict:
    """
    Draft a professional supplier outreach email based on disruption context.
    In production: integrates with Gmail API to send or save as draft.

    Args:
        supplier_name: Name of supplier e.g. "SemiTech Asia"
        supplier_contact: Email contact at supplier
        disruption_context: What disruption is occurring
        ask: What you need from the supplier (expedite, confirm, reroute, etc.)
        sender_name: Name of person/team sending
        company_name: Your company name
    """
    timestamp = datetime.now().strftime("%B %d, %Y")

    email_body = f"""Subject: URGENT: Supply Continuity Request — {disruption_context[:50]}

Dear {supplier_name} Team,

I am reaching out on behalf of {company_name} regarding a developing situation that may impact our supply continuity.

**Situation:**
{disruption_context}

**Our Request:**
{ask}

Given our production commitments to key OEM customers (BMW Group, Volkswagen AG), maintaining supply continuity is critical. We have active production lines that are dependent on your components, and any delay beyond our current safety stock window will result in line stoppages.

We would appreciate your urgent response on the following:
1. Current status of our open purchase orders
2. Your assessment of timeline impact
3. Available options to expedite, reroute, or partially fulfill our order

We are prepared to discuss cost-sharing arrangements if alternative logistics options are required.

Please respond to this message at your earliest convenience, or contact our procurement team directly at procurement@automotiveparts.de or +49 711 XXX-XXXX.

Thank you for your partnership and prompt attention to this matter.

Best regards,
{sender_name}
{company_name}
Supply Chain Risk Management
{timestamp}

---
This communication was flagged as URGENT by our supply chain risk monitoring system.
Reference: SCR-{datetime.now().strftime('%Y%m%d-%H%M')}
"""

    return {
        "status": "success",
        "draft_email": {
            "to": supplier_contact,
            "subject": f"URGENT: Supply Continuity Request — {disruption_context[:50]}",
            "body": email_body,
            "priority": "High",
            "draft_timestamp": datetime.now().isoformat()
        },
        "next_step": "Review draft and approve to send via Gmail API",
        "auto_send_eligible": False,  # Always human-approved for supplier comms
        "reference_id": f"SCR-{datetime.now().strftime('%Y%m%d-%H%M')}"
    }


def send_slack_alert(
    channel: str,
    severity: str,
    disruption_summary: str,
    recommended_action: str,
    financial_exposure_usd: float,
    requires_approval: bool = True
) -> dict:
    """
    Send a Slack escalation alert to operations or executive channel.
    In production: wraps Slack Web API (chat.postMessage).

    Args:
        channel: Slack channel e.g. "#supply-chain-alerts" or "#executive-ops"
        severity: "LOW", "MEDIUM", "HIGH", "CRITICAL"
        disruption_summary: Brief description of the disruption
        recommended_action: What the agent recommends
        financial_exposure_usd: Dollar exposure
        requires_approval: Whether human approval is needed before action
    """
    severity_emoji = {
        "LOW": "🟡",
        "MEDIUM": "🟠",
        "HIGH": "🔴",
        "CRITICAL": "🚨"
    }.get(severity, "⚪")

    message_blocks = [
        {
            "type": "header",
            "text": f"{severity_emoji} Supply Chain Alert — {severity} Severity"
        },
        {
            "type": "section",
            "text": f"*Disruption:* {disruption_summary}"
        },
        {
            "type": "section",
            "text": f"*Financial Exposure:* ${financial_exposure_usd:,.0f}"
        },
        {
            "type": "section",
            "text": f"*Recommended Action:* {recommended_action}"
        },
        {
            "type": "section",
            "text": f"*Requires Approval:* {'✅ Yes — awaiting authorization' if requires_approval else '⚡ Auto-executed'}"
        },
        {
            "type": "context",
            "text": f"Generated by Supply Chain Resilience Agent • {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}"
        }
    ]

    # In production: requests.post("https://slack.com/api/chat.postMessage", ...)
    return {
        "status": "success",
        "channel": channel,
        "severity": severity,
        "message_preview": f"{severity_emoji} [{severity}] {disruption_summary} | Exposure: ${financial_exposure_usd:,.0f}",
        "blocks": message_blocks,
        "sent_at": datetime.now().isoformat(),
        "mock_note": "In production: delivered via Slack Web API"
    }


def flag_erp_reorder_adjustment(
    item_id: str,
    adjustment_type: str,
    new_quantity: int,
    reason: str,
    auto_execute: bool = False
) -> dict:
    """
    Flag or execute a purchase order / reorder point adjustment in the ERP.
    In production: wraps SAP or Oracle ERP REST API.

    Args:
        item_id: ERP item ID e.g. "SEMI-MCU-32"
        adjustment_type: "increase_reorder_point", "emergency_po", "increase_buffer",
                         "pause_po", "expedite_po"
        new_quantity: New quantity value
        reason: Reason for adjustment (used in ERP change log)
        auto_execute: If True, auto-submits. If False, creates pending approval.
    """
    adjustment_descriptions = {
        "increase_reorder_point": f"Reorder point raised to {new_quantity} units",
        "emergency_po": f"Emergency purchase order created for {new_quantity} units",
        "increase_buffer": f"Safety stock target increased to {new_quantity} units",
        "pause_po": f"Open PO paused — {new_quantity} units on hold",
        "expedite_po": f"Expedite flag set on existing PO — priority: {new_quantity}"
    }

    erp_change_record = {
        "change_id": f"ERP-CHG-{datetime.now().strftime('%Y%m%d%H%M%S')}",
        "item_id": item_id,
        "adjustment_type": adjustment_type,
        "description": adjustment_descriptions.get(adjustment_type, f"Adjustment: {adjustment_type}"),
        "quantity": new_quantity,
        "reason": reason,
        "status": "EXECUTED" if auto_execute else "PENDING_APPROVAL",
        "created_at": datetime.now().isoformat(),
        "created_by": "Supply Chain Resilience Agent",
        "approval_required": not auto_execute
    }

    return {
        "status": "success",
        "erp_change": erp_change_record,
        "next_step": "Auto-executed in ERP" if auto_execute else "Awaiting procurement manager approval",
        "mock_note": "In production: submitted via SAP REST API or Oracle Fusion"
    }


def generate_executive_summary(
    disruption_event_json: str,
    risk_assessment_json: str,
    recommended_scenario_json: str,
    actions_taken_json: str
) -> dict:
    """
    Generate a formatted executive summary document for leadership escalation.

    Args:
        disruption_event_json: JSON object with signal data from perception agent (e.g. description, severity, affected_regions)
        risk_assessment_json: JSON object with risk data including total_financial_exposure_usd, total_revenue_at_risk_usd, sla_penalties_at_risk_usd, disruption_duration_days, affected_production_lines
        recommended_scenario_json: JSON object with top-ranked scenario (scenario_name, description, financials.incremental_cost_usd, service_level_protection, timing.implementation_days)
        actions_taken_json: JSON array of action objects (each with description or summary)
    """
    try:
        disruption_event = json.loads(disruption_event_json)
        risk_assessment = json.loads(risk_assessment_json)
        recommended_scenario = json.loads(recommended_scenario_json)
        actions_taken = json.loads(actions_taken_json)
    except (TypeError, json.JSONDecodeError):
        return {"status": "error", "message": "All arguments must be valid JSON strings"}
    if not isinstance(actions_taken, list):
        actions_taken = [actions_taken]
    timestamp = datetime.now().strftime("%B %d, %Y at %H:%M UTC")

    summary_text = f"""
═══════════════════════════════════════════════════════════════
SUPPLY CHAIN RISK EXECUTIVE BRIEF
Generated: {timestamp}
Classification: INTERNAL — OPERATIONS SENSITIVE
═══════════════════════════════════════════════════════════════

SITUATION
─────────
{disruption_event.get('description', 'N/A')}
Severity: {disruption_event.get('severity', 'Unknown')}
Regions Affected: {', '.join(disruption_event.get('affected_regions') or []) if isinstance(disruption_event.get('affected_regions'), list) else str(disruption_event.get('affected_regions', 'N/A'))}

OPERATIONAL IMPACT
──────────────────
• Total Financial Exposure: ${risk_assessment.get('total_financial_exposure_usd', 0):,.0f}
  - Revenue at Risk: ${risk_assessment.get('total_revenue_at_risk_usd', 0):,.0f}
  - SLA Penalties at Risk: ${risk_assessment.get('sla_penalties_at_risk_usd', 0):,.0f}
• Disruption Duration Estimate: {risk_assessment.get('disruption_duration_days', 'TBD')} days
• Production Lines Affected: {len(risk_assessment.get('affected_production_lines', []))}

RECOMMENDED MITIGATION
───────────────────────
Strategy: {recommended_scenario.get('scenario_name', 'N/A')}
Description: {recommended_scenario.get('description', 'N/A')}
Incremental Cost: ${recommended_scenario.get('financials', {}).get('incremental_cost_usd', 0):,.0f}
Service Level Protection: {recommended_scenario.get('service_level_protection', 'N/A')}
Implementation Time: {recommended_scenario.get('timing', {}).get('implementation_days', 'N/A')} days

ACTIONS INITIATED
─────────────────
{chr(10).join(f"• {a.get('description', str(a))}" for a in actions_taken) or "• No actions taken yet"}

DECISION REQUIRED
─────────────────
Please authorize the recommended mitigation strategy within 4 hours to prevent
production line stoppage. Agent is standing by for executive approval.

Contact: AI Operations Co-Pilot | supply-chain-agent@automotiveparts.de
═══════════════════════════════════════════════════════════════
"""

    return {
        "status": "success",
        "summary": summary_text,
        "generated_at": datetime.now().isoformat(),
        "severity": disruption_event.get("severity", "Unknown"),
        "financial_exposure_usd": risk_assessment.get("total_financial_exposure_usd", 0),
        "decision_deadline_hours": 4
    }